# Generated by Django 3.1.2 on 2020-10-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_note',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
